apiVersion: v1
kind: Secret
metadata:
  name: recipe-secret
  namespace: recipe-app
type: Opaque
stringData:
  POSTGRES_PASSWORD: recipepass
  SECRET_KEY: your-super-secret-jwt-key-change-me-in-production
  JWT_ALGORITHM: HS256

